set nocompatible
set nomodeline
set number relativenumber
set backspace=indent,eol,start
set wildmenu
set lazyredraw
set autoread
set nohlsearch
set autoindent
set shiftround
set linebreak
set textwidth=0
set nobackup
set noswapfile
set nowritebackup
set noundofile
set history=50
set ruler
set nowrap
set showcmd
set showmatch
set ignorecase
set incsearch
set pastetoggle=<F12>
set mouse=
set scrolloff=8
set hidden
set nowrap
set nofoldenable
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set path+=**
set laststatus=2
set cmdheight=2
set background=dark
set listchars=tab:→\ ,trail:█
set list

syntax on

if has("autocmd")
    filetype plugin on
endif

if has("multi_byte")
    if &termencoding == ""
        let &termencoding = &encoding
    endif

    set encoding=utf-8
    setglobal fileencoding=utf-8
endif

" Remap Ctrl+A/E to Home/End
noremap <C-a> <Home>
noremap <C-e> <End>
inoremap <C-a> <Home>
inoremap <C-e> <End>
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
